### ISSUE TITLE
Crash when exiting the camera and coming back

### ISSUE THREAD

**Issue by pcm2a** [pvasa/cameraview-ex#144]
On the latest 3.0.1-beta I have been experiencing crashes if I leave the activity and then come back. I have not taken the time to try to reproduce it from the sample app yet. I wanted to see if this is already resolved in any upcoming updates.

```
    java.lang.IllegalStateException: CameraDevice was already closed
        at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2266)
        at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1007)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.stopRepeating(CameraCaptureSessionImpl.java:281)
        at com.priyankvasa.android.cameraviewex.Camera2.releaseCaptureSession(Camera2.kt:676)
        at com.priyankvasa.android.cameraviewex.Camera2.setAspectRatio(Camera2.kt:696)
        at com.priyankvasa.android.cameraviewex.CameraView$1.invoke(CameraView.kt:214)
        at com.priyankvasa.android.cameraviewex.CameraView$1.invoke(CameraView.kt:47)
        at com.priyankvasa.android.cameraviewex.CameraConfigLiveData$observe$1.onChanged(CameraConfigLiveData.kt:46)
```
I updated Camera2.kt and added a try/catch as a test. Afterwards the app no longer crashed and the camera is working good when leaving and returning.

```
    private fun releaseCaptureSession() {
        captureSession?.run {
            try {
                stopRepeating()
                abortCaptures()
                close()
            } catch (e : Exception) {
                println("Error e=" + e.message)
            }
        }
        captureSession = null
    }
```

**Comment by pcm2a** [comment]
Doing more testing and comparing against the develop branch it looks like this is caused by my code to allow swapping between all cameras. Going to close this while I do more investigation.
