### ISSUE TITLE
Failed to open camera with id 0

### ISSUE THREAD

**Issue by AmitPrajapati1902** [pvasa/cameraview-ex#168]
com.sa.enetra E/StreamingFragment$setupCamera: 
        com.priyankvasa.android.cameraviewex.CameraViewException: Failed to open camera with id 0
        at com.priyankvasa.android.cameraviewex.Camera2.start(Camera2.kt:733)
        at com.priyankvasa.android.cameraviewex.CameraView.start(CameraView.kt:496)

Getting error this place.

  @SuppressLint("MissingPermission")
    override fun onResume() {
        super.onResume()

        updateViewState()

        checkPermissions().let { if (it.isEmpty()) camera.start() else requestPermissions(it, 1) }
}

**Comment by pvasa** [comment]
Please use [issue format](https://github.com/pvasa/cameraview-ex/issues/new?template=bug_report.md) to provide more info. Also, the above stacktrace doesn't say much about the actual cause, try to add full trace.
