### ISSUE TITLE
crash in android4.4

### ISSUE THREAD

**Issue by moyaying** [pvasa/cameraview-ex#206]
**Describe the bug**
when run camera.start(), app crash.

**Additional context / stacktrace**
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.leyan.app, PID: 5597
    java.lang.VerifyError: com/priyankvasa/android/cameraviewex/VideoManager
        at com.priyankvasa.android.cameraviewex.Camera1$videoManager$2.invoke(Camera1.kt:88)
        at com.priyankvasa.android.cameraviewex.Camera1$videoManager$2.invoke(Camera1.kt:48)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.priyankvasa.android.cameraviewex.Camera1.getVideoManager(Camera1.kt)
        at com.priyankvasa.android.cameraviewex.Camera1.isVideoRecording(Camera1.kt:186)
        at com.priyankvasa.android.cameraviewex.CameraInterface$DefaultImpls.stop(CameraInterface.kt:62)
        at com.priyankvasa.android.cameraviewex.Camera1.stop(Camera1.kt:337)
        at com.priyankvasa.android.cameraviewex.CameraView.stop(CameraView.kt:660)
        at com.leyan.app.domain.main.MainActivity.onPause(MainActivity.kt:68)
        at android.app.Activity.performPause(Activity.java:5335)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1233)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3034)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3003)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:2981)
        at android.app.ActivityThread.access$1000(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5001)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:575)
        at dalvik.system.NativeStart.main(Native Method)

**Branch Name (if using as a local module)**
3.5.4-alpha

**Comment by pvasa** [comment]
@moyaying Can you please provide a full log and your camera setup code?
