### ISSUE TITLE
Method markState must be called on the main thread

### ISSUE THREAD

**Issue by JohnGeorgiou** [pvasa/cameraview-ex#232]
testing the library and trying to switch cameras using camera.nextCamera();

 FATAL EXCEPTION: CameraViewExBackground
    Process: com.encodica.testkaraoke, PID: 18647
    java.lang.IllegalStateException: Method markState must be called on the main thread
        at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
        at androidx.lifecycle.LifecycleRegistry.markState(LifecycleRegistry.java:109)
        at com.priyankvasa.android.cameraviewex.Camera2.startPreview(Camera2.kt:1131)
        at com.priyankvasa.android.cameraviewex.Camera2.access$startPreview(Camera2.kt:70)
        at com.priyankvasa.android.cameraviewex.Camera2$cameraDeviceCallback$2$1.onOpened(Camera2.kt:129)
        at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:151)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by pvasa** [comment]
fixed by https://github.com/pvasa/cameraview-ex/commit/5084a9128febf69e98d619c124e53cd8f070ebb7

**Comment by tbarseghyan** [comment]
@pvasa can you please publish the latest build to Maven?
