### ISSUE TITLE
Android 11 and 12 I'm facing some issue 

### ISSUE THREAD

**Issue by Bhagirath987** [pvasa/cameraview-ex#235]
I have oneplus nord ce2 device with android 11 version

I have tried to implement this library but when I start app it is showing only white screen 

 - Device: Oneplus nord ce2
 - OS: Android 11

Also I have tried with emulator with android 12

In emulator I'm getting this error while capturing image 

**2022-03-24 16:19:36.598 10182-10374/com.pathquestap E/CameraCaptureSession: Session 0: Exception while stopping repeating: 
    android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
        at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2350)
        at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1277)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:579)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:790)
        at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:259)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)**

![Untitled](https://user-images.githubusercontent.com/76421187/159901524-ed38f068-2cca-40de-b66b-feb669ebfd96.png)
![Screenshot 2022-03-24 162628](https://user-images.githubusercontent.com/76421187/159901821-5ee26c5a-a39b-4574-bc65-3b5190363b51.png)

**Comment by luissantiagodev** [comment]
I'm having the same issue, what fix can be applied?
