### ISSUE TITLE
config.autoFocus.value causes crash when switching cameras

### ISSUE THREAD

**Issue by pcm2a** [pvasa/cameraview-ex#96]
**Describe the bug**
When switching from front to rear or rear to front camera a crash occurs.

Code that causes the crash
`camera.facing = when (camera.facing) {
      Modes.Facing.FACING_BACK -> Modes.Facing.FACING_FRONT
      else -> Modes.Facing.FACING_BACK
 }`

Code causing the crash in Camera2.kt
`config.autoFocus.value = Modes.DEFAULT_AUTO_FOCUS`

Code that resolves the issue
`config.autoFocus.postValue(Modes.DEFAULT_AUTO_FOCUS)`

**To Reproduce**
1. Use the latest version of cameraview-ex from master
2. Run a sample activity that allows switching the camera
3. Experience the crash

**Expected behavior**

**Device (please complete the following information):**
 - Device: LG G6
 - OS: 8.0

**Additional context / stacktrace**
`E/AndroidRuntime: FATAL EXCEPTION: CameraViewExBackground
    Process: com.inthub.greenfly, PID: 1160
    java.lang.IllegalStateException: Cannot invoke setValue on a background thread
        at androidx.lifecycle.LiveData.assertMainThread(LiveData.java:443)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:286)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at com.priyankvasa.android.cameraviewex.CameraConfigLiveData.setValue$cameraViewEx_release(CameraConfigLiveData.kt:33)
        at com.priyankvasa.android.cameraviewex.Camera2.updateAf(Camera2.kt:949)
        at com.priyankvasa.android.cameraviewex.Camera2.updateModes(Camera2.kt:1028)
        at com.priyankvasa.android.cameraviewex.Camera2.access$updateModes(Camera2.kt:62)
        at com.priyankvasa.android.cameraviewex.Camera2$previewSessionStateCallback$1.onConfigured(Camera2.kt:144)
        at java.lang.reflect.Method.invoke(Native Method)
        at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
        at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)`

**Branch Name (if using as a local module)**
- [X] master

**Comment by pvasa** [comment]
Commit https://github.com/pvasa/cameraview-ex/commit/877145f429f13ac42b97d02adedecb5037430768 fixes #96 by running the `LiveData.setValue()` on main thread instead of background handler thread.
